# Numpy indexing and selection 

In [240]:
import numpy as np

In [241]:
arr = np.arange(0,11)

In [242]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [243]:
arr[8]

8

In [244]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [245]:
arr[1:5]

array([1, 2, 3, 4])

In [246]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [247]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [248]:
arr[0:5] = 100

In [249]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [250]:
slice_of_arr = arr[0:6]

In [251]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [252]:
slice_of_arr[:]=99

In [253]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [254]:
arrCopy= arr.copy()

In [255]:
arrCopy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [256]:
arrCopy[:]=100

In [257]:
arrCopy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [258]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [259]:
arrTwoD = np.array([[5,10,15],[20,25,30,],[35,40,45]])

In [260]:
arrTwoD

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [262]:
arrTwoD[1][1]

25

In [263]:
arrTwoD[2][2]

45

In [264]:
arrTwoD[2,2]

45

In [265]:
arrTwoD[1,1]

25

In [269]:
arrTwoD[1]

array([20, 25, 30])

In [272]:
arrTwoD[:2,1:]

array([[10, 15],
       [25, 30]])

In [273]:
array=np.arange(1,11)

In [274]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [275]:
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [276]:
array[array<3]

array([1, 2])

In [277]:
array[array>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [278]:
array[array>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
#create new two d array and reshape to 5 by 10
# grab chunks

In [281]:
arr2d = np.arange(50).reshape(5,10)

In [282]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [283]:
arr2d[1:3]


array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [288]:
arr2d[:5,9:]

array([[ 9],
       [19],
       [29],
       [39],
       [49]])